repository:
    # Repository name
    name: Electron-Typescript-React-Boilerplate

    # Enable issues
    has_issues: true

    # Disable projects
    has_projects: false

    # Disable wiki
    has_wiki: false

    # Disable downloads
    has_downloads: true

    # Enable delete branch on merge
    delete_branch_on_merge: true

    # Enable automatic branch updates
    allow_update_branch: true

    # Merge settings
    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false
    squash_merge_commit_title: PR_TITLE
    squash_merge_commit_message: COMMIT_MESSAGES

    # Branch protection rules
branches:
    - name: main
      protection:
          # Require pull request reviews before merging
          required_pull_request_reviews:
              required_approving_review_count: 1
              dismiss_stale_reviews: true
              require_code_owner_reviews: false
              require_last_push_approval: true
              required_review_thread_resolution: true

          # Required status checks
          required_status_checks:
              strict: true
              contexts:
                  - "quality"
                  - "build (ubuntu-latest)"
                  - "build (windows-latest)"
                  - "build (macos-latest)"

          # Allow admins to bypass restrictions
          enforce_admins: false

          # No restrictions on who can push (admins can bypass protection anyway)
          restrictions: null

          # Require linear history
          required_linear_history: true

          # Allow force pushes (admins only since enforce_admins is false)
          allow_force_pushes: true

          # Allow deletions
          allow_deletions: false
