name: Trigger Build

on:
    workflow_dispatch:
        inputs:
            ref:
                description: 'Branch, tag or SHA to build'
                required: true
                default: 'main'

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Trigger build workflow
              uses: actions/github-script@v7
              with:
                  script: |
                    await github.rest.actions.createWorkflowDispatch({
                        owner: context.repo.owner,
                        repo: context.repo.name,
                        workflow_id: 'build.yml',
                        ref: '${{ github.event.inputs.ref }}'
                    });